services:
  db:
    image: postgis/postgis:15-3.4 # Use the PostGIS enabled image
    container_name: nyc_311_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  populate_db:
    build:
      context: ./populate_db
    container_name: nyc_311_populator
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
